# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70e0d65293e75792d100cff3f39412525601eb162e87e59dc2e380d94870bf38199f067e9e318543a1842844304d6f9be334e6ae269835e77eee42bde0b3f907

test:
  secret_key_base: d858bd5adeaf6b3947109ac950b308c6882b05d78e70bfd39b4333de089ae03b36d43d71bfa8bfbd70e5618a739c37f9fdb00b32ee45eac8dd22dddd50c37b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
